@startuml LendCommandSequenceDiagram
skinparam defaultFontName Arial
skinparam sequenceArrowThickness 1.5
skinparam sequenceParticipantBorderColor #555555
skinparam sequenceParticipantBackgroundColor #FEFEFE
skinparam sequenceLifeLineBorderColor #777777
skinparam shadowing false

participant ":SpendSwift" as main #LightCyan
participant "<<class>>\nParser" as parser #D5E8D4
participant ":ExpenseList" as el #DAE8FC
participant ":Ui" as ui #FFF9C4

User -> main : "lend 20 Alice"
activate main

main -> parser : parse("lend 20 Alice", ui)
activate parser

create participant "a:LendCommand" as cmd #D5E8D4
parser -> cmd : new LendCommand(ui, "Alice", 20.0, null)
activate cmd
cmd --> parser
deactivate cmd

parser --> main : a
deactivate parser

main -> cmd : execute(expenseList)
activate cmd

create participant "l:Loan" as loan #FCE5CD
cmd -> loan : new Loan("Alice", 20.0, null)
activate loan
loan --> cmd
deactivate loan

cmd -> el : addLoan(l)
activate el
el --> cmd
deactivate el

cmd -> ui : showLendAdded(l, size)
activate ui
ui --> cmd
deactivate ui

cmd --> main
deactivate cmd
@enduml